export function renderJournal({ linkButton, media }) {
  const stories = [
    ['Material notes','How to read a fabric sample','A practical way to compare texture, colour and construction before choosing upholstery.','/assets/textile-editorial.jpg','/materials.html'],
    ['Care & keeping','Living with velvet','Pile direction, everyday use and why a sample should be viewed in changing light.','/assets/stitch/stitch-velvet.png','/materials.html'],
    ['Workshop stories','The value of keeping good bones','What to consider when deciding whether a piece is ready for reupholstery.','/assets/stitch/stitch-craftsman.png','/services.html'],
    ['Room studies','One chair, a new point of view','See how an accent piece can shift a room through colour and texture.','/assets/chair-editorial.jpg','/catalogue.html'],
  ]
  return `<section class="page-banner journal-banner"><div><p class="spec-label gold-text">NOTES FROM THE WORKSHOP</p><h1>Good things take<br><strong>a closer look.</strong></h1><p>Material guidance, care ideas and stories about the furniture we choose to keep.</p></div><img src="/assets/interior-editorial.jpg" alt="Editorial upholstery interior"></section><section class="section journal-feature"><div>${media('/assets/sofa-editorial.jpg','Sofa in a softly lit room')}</div><div><p class="spec-label gold-text">FEATURED / MATERIAL NOTES</p><h2>Choose by touch.<br><strong>Confirm in the room.</strong></h2><p>A fabric can look different under daylight, warm lamps and the colour of the walls around it. Take a cutting home, live with it for a moment and ask how the furniture will be used.</p>${linkButton('Browse material guidance','/materials.html','ghost')}</div></section><section class="section journal-grid">${stories.map(([category,title,copy,image,path]) => `<article class="journal-card"><a href="${path}"><img src="${image}" alt="" loading="lazy"><div><small>${category}</small><h2>${title}</h2><p>${copy}</p><span>READ THE NOTE ↗</span></div></a></article>`).join('')}</section>`
}
