export function renderStudio({ materials }) {
  return `<section class="ai-studio" id="ai-studio">
    <header class="studio-heading"><div><p class="spec-label gold-text">UPHOLSTERY WAREHOUSE / AI STUDIO</p><h1>Your furniture.<br><em>Another possibility.</em></h1></div><p>One photo. Every texture. Select the upholstery, explore a new surface, and see your room in a different light.</p></header>
    <div class="studio-workspace">
      <div class="studio-main"><div class="studio-topbar"><div class="studio-mode"><button id="studio-photo" aria-pressed="true">01 / Photograph</button><button id="studio-camera" aria-pressed="false">02 / Live camera <small>BETA</small></button><button id="studio-pbr" aria-pressed="false">Inspect in 3D ↗</button></div><span id="studio-engine">PRIVATE · ON YOUR DEVICE</span></div>
        <div class="studio-stage" id="studio-stage"><canvas id="studio-canvas" width="1000" height="750" tabindex="0" role="img" aria-label="Furniture preview. Tap upholstery to select it, or use the brush to paint a selection."></canvas><div class="studio-empty" id="studio-empty"><span class="studio-orbit">✧</span><h2>Reimagine what<br>you already love.</h2><p>Drop a furniture photograph here.<br>JPG, PNG or WebP · up to 15 MB</p><button class="button gold" type="button" data-studio-upload>Upload a photograph ↗</button><button id="studio-demo" class="text-link">Or explore the studio sofa</button></div><span id="studio-stage-label" hidden>LOCAL MATERIAL PREVIEW</span><div id="studio-busy" hidden><i></i><span>Finding your furniture…</span></div></div>
        <div class="studio-pbr-panel" id="studio-pbr-panel" hidden><div id="studio-pbr-host"></div><p id="studio-pbr-status" role="status"></p><small>Generic sofa study · drag to rotate · scroll to zoom. This is not a reconstruction of your uploaded furniture.</small></div>
        <div class="studio-comparison" id="studio-comparison" hidden><span>ORIGINAL</span><label for="studio-compare">Drag to compare</label><span>NEW MATERIAL</span></div>
        <div class="studio-status" id="studio-status" role="status" aria-live="polite">Start with a photograph or enable your camera.</div>
        <div class="studio-editbar"><button class="studio-upload-button" type="button" data-studio-upload>＋ New photo</button><input id="studio-upload" type="file" accept="image/jpeg,image/png,image/webp" hidden><div role="group" aria-label="Selection tools"><button data-studio-tool="ai" aria-pressed="true">✧ AI select</button><button data-studio-tool="paint" aria-pressed="false">＋ Brush</button><button data-studio-tool="erase" aria-pressed="false">− Erase</button></div><button id="studio-undo">↶ Undo</button><button id="studio-clear">Clear selection</button><button id="studio-stop" hidden>Stop camera</button></div>
        <div class="studio-sliders"><label>Brush size<input id="studio-brush" type="range" min="5" max="120" value="35"></label><label>Texture scale<input id="studio-scale" type="range" min="30" max="350" value="130"></label><label>Material strength<input id="studio-strength" type="range" min="0" max="100" value="95"></label><label>Before / after<input id="studio-compare" type="range" min="0" max="100" value="50"></label><label>Weave direction<input id="studio-rotation" type="range" min="0" max="180" value="0"></label><label>Surface softness<input id="studio-softness" type="range" min="0" max="100" value="50"></label></div>
        <div class="studio-actions"><label><input id="studio-mask-toggle" type="checkbox"> Show selection</label><button id="studio-capture" hidden>Freeze frame</button><button class="button gold" id="studio-export" disabled>Download preview ↓</button></div>
        <div class="studio-editbar"><button id="studio-xr">Try 8th Wall camera ↗</button><a class="text-link" href="https://8thwall.org/" target="_blank" rel="noreferrer">8th Wall engine</a></div>
        <p class="studio-hint">Tap the fabric with AI select. Brush adds missed areas; Erase protects legs and the room. Live mode refreshes the selection while you hold the camera steady. A surface study, not a measured fabric simulation.</p>
      </div>
      <aside class="studio-library"><div class="studio-library-heading"><span>THE SURFACE EDIT</span><h2>Change the feel.</h2><p><b>${materials.length}</b> material directions, ready to try.</p></div><label class="studio-search">Find a fabric<input id="studio-search" type="search" placeholder="Velvet, linen, leather…"></label><label class="studio-family">Surface family<select id="studio-family"><option value="all">All materials</option>${[...new Set(materials.map(m=>m.group))].map(g=>`<option>${g}</option>`).join('')}</select></label><div class="studio-selected" id="studio-selected"></div><div id="studio-swatches" class="studio-swatches" aria-label="Choose a material"></div><p class="studio-library-note">Supplier colourways are indicative. CC0 texture studies credit their source. Always confirm with a physical sample.</p><a class="text-link" href="/materials.html">Explore the material library ↗</a></aside>
    </div>
    <section class="studio-method"><div><span>01 / SELECT</span><h3>Keep the shape.</h3><p>AI finds the object you tap. Refine the upholstery boundary yourself for a more precise finish.</p></div><div><span>02 / EXPLORE</span><h3>Follow the texture.</h3><p>Compare materials with the original photo. Lighting and shadows remain visible through the new surface.</p></div><div><span>03 / TAKE IT FURTHER</span><h3>See it live.</h3><p>Use your camera for an experimental live surface preview. Freeze a frame to refine and save your direction.</p></div></section>
  </section>`
}
